repo_name: /weijiacheng
#site_name: My Website
site_name: Jeff Wei分享站点
nav:
#    - Home: index.html
    - 站点地图: contents
    - 首页: contents/home
    - 数学: contents/math
    - 语文: contents/chinese
    - 英语: contents/english
    - 编程: contents/programming
    - 收藏: contents/favorites
    - About: contents/wjch/about-me
#theme: readthedocs
#repo_url: https://github.com/onhalfway/weijiacheng

extra:
    search:
        language: 'jp'
# theme:
#     language: 'zh'
