repo_name: /weijiacheng
#site_name: My Website
site_name: Jeff Wei分享站点
nav:
#    - Home: index.html
    - 站点地图: contents
    - 首页: contents/home
    - 语文: contents/chinese
    - 英语: contents/english
    - 编程: contents/programming
    - 收藏: contents/favorites
#theme: readthedocs
# C:\Users\kehwei\AppData\Local\Programs\Python\Python37\Lib\site-packages\mkdocs\themes\
# mkdocs build --help
# mkdocs build --clean
# mkdocs gh-deploy --clean -v
#repo_url: https://github.com/onhalfway/weijiacheng